
development:
  adapter: mysql2
  database: dashboard
  username: root
  password: re9hav2GY
  host: localhost

test:
  adapter: mysql2
  database: dashboard_test
  username: root
  password: re9hav2GY
  host: localhost

production:
  adapter: mysql2
  database: dashboard
  username: root
  password: re9hav2GY
  host: localhost